export const customErrorMapping = {
  "database.error.insert": "Erro ao incluir registro",
  "database.error.update": "Erro ao alterar o registro",
  "database.error.delete": "Erro ao excluir o registro",
  "record.error.notFound": "Registro não encontrado",
  "audience.error.name.null": "Nome da audiência não pode ser nulo",
  "audience.error.name.larger": "Nome da audiência deve ter no máximo 50 caracteres",
  "audience.error.name.exists": "Já existe uma audiência com este nome",
  "audience.error.query.null": "Consulta (query) não pode ser nua",
  "audience.error.query.cpf.notFound": "O retorno deve ser uma lista com nome cpf",
  "audience.param.error.name.null": "Nome do parâmetro não pode ser nulo",
  "audience.param.error.name.larger": "Nome do parâmetro deve ter no máximo 20 caracteres",
  "audience.param.error.typecast.null": "Tipo do parâmetro não pode ser nulo",
  "audience.param.error.title.null": "Título do parâmetro não pode ser nulo",
  "audience.param.error.title.larger": "Título do parâmetro deve ter no máximo 50 caracteres",
  "audience.param.error.typecast.invalid": "Titpo do parâmtero é inválido",
  "appTarget.error.name.exists": "Nome já existe",
  "appTarget.error.name.null": "Nome é obrigatório",
  "appTarget.error.route.null": "Rota é obrigatório",
  "appTarget.param.error.name.null": "Nome do parâmetro é obrigatório",
  "appTarget.param.error.name.larger": "Nome do parâmetro deve ter no máximo 20 caracteres.",
  "appTarget.param.error.typecast.null": "Tipo do parâmetro é obrigatório",
  "appTarget.param.error.title.null": "Título do parâmetro é obrigatório",
  "appTarget.param.error.title.larger": "Título do parâmetro deve ter no máximo 50 caracteres",
  "appTarget.param.error.typecast.invalid": "Tipo de parâmetro inválido",
  "campaign.error.channel.notFound": "Canal não encontrado",
  "campaign.error.channel.null": "Canal é obrigatório",
  "campaign.error.appTarget.notFound": "Alvo no aplicativo não encontrado",
  "campaign.error.appTarget.null": "Alvo no aplicativo é obrigatório",
  "campaign.error.audience.notFound": "Audiência não encontrada",
  "campaign.error.audience.null": "Audiência é obrigatória",
  "campaign.error.conversionEvent.notFound": "Evento de conversão não encontrado",
  "campaign.error.conversionEvent.null": "Evento de conversão é obrigatório",
  "campaign.error.notification.notFound": "Notificação não encontrada",
  "campaign.error.notification.null": "Notificação é obrigatória",
  "campain.error.status.null": "Situação é obrigatória",
  "campain.error.scheduling.null": "Agendamento é obrigatório",
  "campaign.error.update.status.invalid": "O registro não pode ser alterado. Favor verificar o status.",
  "campaign.error.delete.status.invalid": "O registro não pode ser excluído. Favor verificar o status.",
  "channel.error.name.larger": "O nome do canal deve ter no máximo 50 caracteres",
  "conversionEvent.error.name.larger": "O nome deve ter no máximo 50 caracteres",
  "conversionEvent.error.name.exists": "Nome já existe",
  "conversionEvent.error.name.null": "Nome é obrigatório",
  "conversionEvent.error.title.larger": "O título deve ter no máximo 50 caracteres",
  "notification.error.title.larger": "O título deve ter no máximo 50 caracteres",
  "notification.error.title.exists": "Título já existe",
  "notification.error.title.null": "Título é obrigatório",
  "user.error.password.invalid": "Senha inválida",
  "department.error.name.exists": "Departamento já existe",
  "script.error.name.exists": "Já existe um script com este nome",
  "user.error.name.exists": "Já existe um usuário com este nome",
  "position.error.name.exists": "Já existe um cargo com este nome",
  "positionGroup.error.name.exists": "Já existe um grupo de cargo com este nome",
  "default.error.notFound": "Registro não encontrado",
};
